# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
    paths:
      - dungeondb2_*/*
      - seadb2_*/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build
        run: |
          npm install
          npm run build
        env:
          UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
          clean: false
  
